services:
  gpp:
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/tmp/.Xauthority:ro