# ====================================================================
# Game SFX Configuration
# ====================================================================
# Format:			SFX_TYPE=path/to/sfx.wav;cooldown;priority
#
# Cooldowns:		duration (in seconds) per SFX_TYPE
#
#	- 0.05s - 0.15s = Fast/responsive (UI, footsteps)
#	- 0.20s - 0.40s = Medium (Combat, Jumps)
#	- 0.50s - 2.00s = Slow (Death, Reload, Explosions)
#
# Priority Levels:	Higher priority SFX interrupts lower priority SFX
#					Range: Low 0 to High 10
#
#	- 1 - 2 		= Ambient (footsteps, background)
#	- 3 - 4 		= Feedback (UI, pickups)
#	- 5 - 6 		= Combat (attacks, weapons)
#	- 7 - 8 		= Important (damage, explosions)
#	- 9 - 10 		= Critical (death, victory)
#
# Example cooldowns:
#	- 0.15f			SFX_WALKING: step...step...step
#	- 0.30f			SFX_JUMPING: Bong......Bong
#	- 0.20f			SFX_ATTACKING: Slash....Slash
#	- 0.25f			SFX_PICKUP: Ching....Ching
#	- 0.40f			SFX_DAMAGE: Ohhhh........Ohhhh
#	- 1.00f			SFX_DEATH: Arrrrrrrggggggooohhh
#	- 0.10f			SFX_UI_SELECT: Ping..Ping
#	- 0.12f			SFX_FIRE: Tat..Tat..Tat
#	- 1.50f			SFX_RELOAD: Chickchick
#	- 0.50f			SFX_EXPLOSION: Boom....boom
#
# Example priorities:
#	- 2				SFX_WALKING: Low priority, ambient
#	- 4				SFX_JUMPING: Medium priority
#	- 5				SFX_ATTACKING: Mid high Combat
#	- 3				SFX_PICKUP: Low priority feedback
#	- 7				SFX_DAMAGE: High priority feedback
#	- 9				SFX_DEATH: High priority critical event
#	- 3				SFX_UI_SELECT: Low priortiy UI feedback
#	- 6				SFX_FIRE: Mid priority combat
#	- 5				SFX_RELOAD: Mid priority important feedback for combat
#	- 8				SFX_EXPLOSION: High priority big event
# ====================================================================

# ====================================================================
# Movement and Locomotion
# ====================================================================
SFX_RUNNING					=assets/sfx/slimerun.wav;0.01;2
SFX_JUMPING					=assets/sfx/slimejump.wav;0.01;4
SFX_LANDING					=assets/sfx/slimelanding.wav;0.01;4

# ====================================================================
# User Interface
# ====================================================================
SFX_UI_SELECT				=assets/sfx/ui/ui_select.wav;0.10;3
SFX_UI_CONFIRM				=assets/sfx/ui/ui_confirm.wav;0.15;5
SFX_UI_CANCEL				=assets/sfx/ui/ui_cancel.wav;0.15;4
SFX_UI_ERROR				=assets/sfx/ui/ui_error.wav;0.20;5
SFX_PAUSE					=assets/sfx/other/pause.wav;0.25;6
SFX_UNPAUSE					=assets/sfx/other/unpause.wav;0.25;6

# ====================================================================
# Achievements SFX
# ====================================================================
SFX_ACHIEVEMENT_LEVEL		= ./assets/sfx/other/achievement_level_sound.wav;0.0;8
SFX_ACHIEVEMENT_COMBAT		= ./assets/sfx/other/achievement_combat_sound.wav;0.0;8
SFX_ACHIEVEMENT_COLLECTION	= ./assets/sfx/other/achievement_collection_sound.wav;0.0;8