# ====================================================================
# Game Audio Tracks Configuration
# ====================================================================
MUSIC_MENU					=assets/tracks/menu.ogg
MUSIC_GAMEPLAY				=assets/tracks/gameplay.ogg
MUSIC_VICTORY				=assets/tracks/gameplay.ogg
MUSIC_GAMEOVER				=assets/tracks/menu.ogg